### ISSUE TITLE
Null Issue

### ISSUE THREAD

**Issue by DCBoy001** [FlyingPikachu/Quests#259]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
Quests-3.2.3

(__Required__) Please describe the problem and how to replicate it. Any console errors?
This is my first time using quest, but when I try to load the plugin on my 1.8 server. (Yes, 1.12 is released and even lower version, but I want to stay on 1.8). It will give an error: https://pastebin.com/08sVwR1v, but shows green in /plugins but whenever I type a command it will show this: http://prntscr.com/i63gyq. And I have no clue how to resolve this or what version I should use on a 1.8 server. 

(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
N/A

Hopefully this can get resolved, or I get help to resolve this.
Thanks already!

- Thomas.

**Comment by FlyingPikachu** [comment]
Duplicate of #258

What operating system (Windows/Mac/Linux) are you hosting your server on?

**Comment by FlyingPikachu** [comment]
The following dev build should resolve this issue. Thanks for using Quests!

http://ci.ac3-servers.eu/job/Quests/249/

**Comment by DCBoy001** [comment]
Still doesn't work. I replaced the quests.yml file and deleted the folder. Restarted the server and every command still displayes "NULL".

**Comment by FlyingPikachu** [comment]
@DCBoy001 Can you post the new error (even if it looks similar)?

**Comment by DCBoy001** [comment]
It doesn't give an error. In console it just loads up fine. But ingame every command is /quest null. Even /quest or /help quest.

**Comment by FlyingPikachu** [comment]
Alright, could you post a startup log of your server? And are you running on Windows, Mac or Linux?

**Comment by DCBoy001** [comment]
[19:18:29] [Server thread/INFO]: Starting minecraft server version 1.8.8
[19:18:29] [Server thread/INFO]: Loading properties
[19:18:29] [Server thread/INFO]: Default game type: SURVIVAL
[19:18:29] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[19:18:30] [Server thread/INFO]: Debug logging is disabled
[19:18:30] [Server thread/INFO]: Server Ping Player Sample Count: 12
[19:18:30] [Server thread/INFO]: Using 4 threads for Netty based IO
[19:18:30] [Server thread/INFO]: Generating keypair
[19:18:32] [Server thread/INFO]: Starting Minecraft server on *:25565
[19:18:32] [Server thread/INFO]: Using default channel type
[19:18:33] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Loading AsyncWorldEditInjector v2.3.0
[19:18:35] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.8-SNAPSHOT;cd4729f
[19:18:35] [Server thread/INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v2.3.3
[19:18:35] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[19:18:35] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.1
[19:18:35] [Server thread/INFO]: [CraftZ] Loading CraftZ v1.0
[19:18:35] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.16-SNAPSHOT (build 1267)
[19:18:35] [Server thread/INFO]: [AreaShop] Loading AreaShop v2.4.0
[19:18:35] [Server thread/INFO]: [Quests] Loading Quests v3.2.3-b249
[19:18:35] [Server thread/INFO]: [Essentials] Loading Essentials v2.0.1-b577
[19:18:35] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.0.1-b577
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v2.3.0
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.SchematicCommands injected.
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.ScriptingCommands injected.
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.RegionCommands injected.
[19:18:35] [Server thread/INFO]: [AsyncWorldEditInjector] Enabled
[19:18:35] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[19:18:36] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[19:18:36] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[19:18:36] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[19:18:36] [Server thread/INFO]: [CraftZ] Enabling CraftZ v1.0
[19:18:37] [Server thread/INFO]: [CraftZ] Successfully hooked into Vault. Players can receive rewards.
[19:18:37] [Server thread/INFO]: [CraftZ] ++=============================================++
[19:18:37] [Server thread/INFO]: [CraftZ] ||  Visit dev.bukkit.org/bukkit-plugins/craftz ||
[19:18:37] [Server thread/INFO]: [CraftZ] ||  Plugin successfully enabled.               ||
[19:18:37] [Server thread/INFO]: [CraftZ] ++=============================================++
[19:18:37] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[19:18:37] [Server thread/INFO]: Preparing level "world"
[19:18:37] [Server thread/INFO]: -------- World Settings For [world] --------
[19:18:37] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:18:37] [Server thread/INFO]: Arrow Despawn Rate: 1200
[19:18:37] [Server thread/INFO]: Item Despawn Rate: 6000
[19:18:37] [Server thread/INFO]: Item Merge Radius: 2.5
[19:18:37] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[19:18:37] [Server thread/INFO]: View Distance: 10
[19:18:37] [Server thread/INFO]: Experience Merge Radius: 3.0
[19:18:37] [Server thread/INFO]: Chunks to Grow per Tick: 650
[19:18:37] [Server thread/INFO]: Clear tick list: false
[19:18:37] [Server thread/INFO]: Max Entity Collisions: 8
[19:18:37] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[19:18:37] [Server thread/INFO]: Mob Spawn Range: 4
[19:18:37] [Server thread/INFO]: Sending up to 10 chunks per packet
[19:18:37] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:18:37] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:18:37] [Server thread/INFO]: Structure Info Saving: true
[19:18:37] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[19:18:37] [Server thread/INFO]: Cactus Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Cane Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Melon Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Sapling Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Wheat Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[19:18:37] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[19:18:37] [Server thread/INFO]: Max TNT Explosions: 100
[19:18:37] [Server thread/INFO]: Anti X-Ray: true
[19:18:37] [Server thread/INFO]: 	Engine Mode: 1
[19:18:37] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[19:18:37] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[19:18:37] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:18:37] [Server thread/INFO]: Random Lighting Updates: false
[19:18:38] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[19:18:38] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:18:38] [Server thread/INFO]: Arrow Despawn Rate: 1200
[19:18:38] [Server thread/INFO]: Item Despawn Rate: 6000
[19:18:38] [Server thread/INFO]: Item Merge Radius: 2.5
[19:18:38] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[19:18:38] [Server thread/INFO]: View Distance: 10
[19:18:38] [Server thread/INFO]: Experience Merge Radius: 3.0
[19:18:38] [Server thread/INFO]: Chunks to Grow per Tick: 650
[19:18:38] [Server thread/INFO]: Clear tick list: false
[19:18:38] [Server thread/INFO]: Max Entity Collisions: 8
[19:18:38] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[19:18:38] [Server thread/INFO]: Mob Spawn Range: 4
[19:18:38] [Server thread/INFO]: Sending up to 10 chunks per packet
[19:18:38] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:18:38] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:18:38] [Server thread/INFO]: Structure Info Saving: true
[19:18:38] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[19:18:38] [Server thread/INFO]: Cactus Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Cane Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Melon Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Sapling Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Wheat Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[19:18:38] [Server thread/INFO]: Max TNT Explosions: 100
[19:18:38] [Server thread/INFO]: Anti X-Ray: true
[19:18:38] [Server thread/INFO]: 	Engine Mode: 1
[19:18:38] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[19:18:38] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[19:18:38] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:18:38] [Server thread/INFO]: Random Lighting Updates: false
[19:18:38] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[19:18:38] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[19:18:38] [Server thread/INFO]: Arrow Despawn Rate: 1200
[19:18:38] [Server thread/INFO]: Item Despawn Rate: 6000
[19:18:38] [Server thread/INFO]: Item Merge Radius: 2.5
[19:18:38] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[19:18:38] [Server thread/INFO]: View Distance: 10
[19:18:38] [Server thread/INFO]: Experience Merge Radius: 3.0
[19:18:38] [Server thread/INFO]: Chunks to Grow per Tick: 650
[19:18:38] [Server thread/INFO]: Clear tick list: false
[19:18:38] [Server thread/INFO]: Max Entity Collisions: 8
[19:18:38] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[19:18:38] [Server thread/INFO]: Mob Spawn Range: 4
[19:18:38] [Server thread/INFO]: Sending up to 10 chunks per packet
[19:18:38] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[19:18:38] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[19:18:38] [Server thread/INFO]: Structure Info Saving: true
[19:18:38] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[19:18:38] [Server thread/INFO]: Cactus Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Cane Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Melon Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Sapling Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Wheat Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[19:18:38] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[19:18:38] [Server thread/INFO]: Max TNT Explosions: 100
[19:18:38] [Server thread/INFO]: Anti X-Ray: true
[19:18:38] [Server thread/INFO]: 	Engine Mode: 1
[19:18:38] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[19:18:38] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[19:18:38] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[19:18:38] [Server thread/INFO]: Random Lighting Updates: false
[19:18:38] [Server thread/INFO]: Preparing start region for level 0 (Seed: 27594263)
[19:18:39] [Server thread/INFO]: Preparing spawn area: 43%
[19:18:40] [Server thread/INFO]: Preparing spawn area: 94%
[19:18:40] [Server thread/INFO]: Preparing start region for level 1 (Seed: -3787311316323310178)
[19:18:41] [Server thread/INFO]: Preparing spawn area: 10%
[19:18:42] [Server thread/INFO]: Preparing spawn area: 51%
[19:18:43] [Server thread/INFO]: Preparing start region for level 2 (Seed: -3787311316323310178)
[19:18:44] [Server thread/INFO]: Preparing spawn area: 81%
[19:18:44] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.8-SNAPSHOT;cd4729f
[19:18:45] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[19:18:45] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_8_R3 as the Bukkit adapter
[19:18:45] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v2.3.3
[19:18:45] [Server thread/INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix
[19:18:45] [Server thread/INFO]: [AsyncWorldEditInjector] New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
[19:18:46] [Server thread/INFO]: [AsyncWorldEdit] You have an old version of the plugin. Your version: 2.3.3, available version: 3.4.11
[19:18:46] [Server thread/INFO]: [AsyncWorldEdit] Enabled
[19:18:46] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.1
[19:18:46] [Server thread/INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world) Lava fire is blocked.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_nether) Lava fire is blocked.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_the_end) Lava fire is blocked.
[19:18:46] [Server thread/INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[19:18:46] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[19:18:46] [Server thread/INFO]: [WorldGuard] Loading region data...
[19:18:46] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.16-SNAPSHOT (build 1267)
[19:18:48] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.4.0
[19:18:49] [Server thread/INFO]: [Quests] Enabling Quests v3.2.3-b249
[19:18:49] [Server thread/ERROR]: [Quests] Failed loading lang files for en-US because they were not found. Using default en-US
[19:18:49] [Server thread/INFO]: [Quests] Loaded language en-US. Translations via Crowdin
[19:18:49] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b577
[19:18:49] [Server thread/INFO]: Attempting to convert old kits in config.yml to new kits.yml
[19:18:49] [Server thread/INFO]: No kits found to migrate.
[19:18:49] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[19:18:49] [Server thread/INFO]: [Essentials] Using legacy item data provider as spawn egg provider.
[19:18:49] [Server thread/INFO]: [Essentials] Using legacy potion meta provider as potion meta provider.
[19:18:49] [Server thread/INFO]: Using locale nl_NL
[19:18:50] [Server thread/INFO]: [Essentials] Using Spigot 1.7.10+ ServerListPingEvent iterator
[19:18:50] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[19:18:50] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[19:18:50] [Server thread/INFO]: [Essentials] Using superperms-based permissions.
[19:18:50] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.0.1-b577
[19:18:50] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:18:50] [Server thread/INFO]: Done (12.648s)! For help, type "help" or "?"
[19:18:50] [Server thread/INFO]: [CraftZ] Loaded 0 chests, 1 player spawns, 1 zombie spawns
[19:18:51] [Server thread/INFO]: [Citizens] 0 NPCs geladen.
[19:18:52] [Craft Scheduler Thread - 4/INFO]: [Vault] Checking for Updates ... 
[19:18:52] [Server thread/INFO]: [Quests] 4 Quest(s) loaded.
[19:18:52] [Server thread/INFO]: [Quests] 8 Event(s) loaded.
[19:18:52] [Server thread/INFO]: [Quests] 0 Phrase(s) loaded.
[19:18:58] [Craft Scheduler Thread - 4/INFO]: [Vault] No new version available
[19:19:16] [Timer-1/INFO]: [WorldGuard] Region data changes made in 'world' have been background saved

**Comment by FlyingPikachu** [comment]
Fix available soon at http://ci.ac3-servers.eu/job/Quests/250/
