### ISSUE TITLE
New Users not creating Data file; console spam.

### ISSUE THREAD

**Issue by Formula350** [FlyingPikachu/Quests#32]
Despite the config being set to Create File on Join, it appears as though after updating to v2.2.2 earlier today, that new players (not sure if ALL new player, or not) may not be creating a Data file, causing this error to spam the console:

26.02 21:40:34 [Server] ERROR Quester not found for UUID "d5658441-b9d2-441d-a26f-1df68c9e4658". Consider adding it to the Quester blacklist.
26.02 21:40:34 [Server] ERROR Quester not found for UUID "d5658441-b9d2-441d-a26f-1df68c9e4658". Consider adding it to the Quester blacklist.
26.02 21:40:33 [Server] ERROR Quester not found for UUID "d5658441-b9d2-441d-a26f-1df68c9e4658". Consider adding it to the Quester blacklist.
26.02 21:40:33 [Server] ERROR Quester not found for UUID "d5658441-b9d2-441d-a26f-1df68c9e4658". Consider adding it to the Quester blacklist.
26.02 21:40:32 [Server] ERROR Quester not found for UUID "d5658441-b9d2-441d-a26f-1df68c9e4658". Consider adding it to the Quester blacklist.

Of course, replace the UUID with that of the couple others that have caused the same error:
60e7aed8-230a-4b57-9569-f643a334bc64
eb2f7c4b-01a3-4b1d-abff-b00234083c4d
252d80fe-0c9f-491e-bd34-18747257ff8e
That last one just happened right now in real time. Player picked their Class, and a few moments later up popped the error. Another new person just joined as well... and... they too did not create a file. Yet this person seems to have joined after I updated to v2.2.2 and they have a file:
60ded38e-8925-42cf-b2ac-f71f0f7857b0

I also manually created a file for one of them and while he didn't create errors anymore, he said he wasn't able to talk to an NPC, so it seems the plugin still doesn't quite recognize the player despite that fact.

As usual any further info I can provide, I'll do my best!

**Comment by Formula350** [comment]
Oh, I see v2.2.2 is persistent across a few builds. Mine is Build #38

**Comment by Formula350** [comment]
Oh, I see v2.2.2 is persistent across a few builds. Mine is Build# 38

**Comment by FlyingPikachu** [comment]
I feel this may be related to your previous ticket. Please try Quests v2.2.3 and post back if the issue persists.

**Comment by Formula350** [comment]
Will do, thanks.

I wasn't entirely sure if it was related or not. Sorry about that :P I'll let you know!

**Comment by Formula350** [comment]
I should point out that 1) This console log is upside-down, because MultiCraft is annoying like that, 2) I loaded this plugin while the server was live, so if it needs a restart in order properly work, I'll try to do that later tonight when fewer players are on.

That being said, it looks like the UUID issue is not showing up, BUT there's an even spammier error now, similar to the other thread's Entity error:

``` java

27.02 16:41:12 [Server] INFO ... 21 more
27.02 16:41:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
27.02 16:41:12 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
27.02 16:41:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
27.02 16:41:12 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
27.02 16:41:12 [Server] INFO at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:655) ~[?:?]
27.02 16:41:12 [Server] INFO Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
27.02 16:41:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
27.02 16:41:12 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1245) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1036) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:996) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.EntityMonster.damageEntity(EntityMonster.java:44) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:768) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:830) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:346) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:12 [Server] INFO org.bukkit.event.EventException
27.02 16:41:12 [Server] ERROR Could not pass event EntityDeathEvent to Quests v2.2.3
27.02 16:41:08 [Server] INFO ... 22 more
27.02 16:41:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
27.02 16:41:08 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
27.02 16:41:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
27.02 16:41:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
27.02 16:41:08 [Server] INFO at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:655) ~[?:?]
27.02 16:41:08 [Server] INFO Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
27.02 16:41:08 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
27.02 16:41:08 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1245) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1036) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:996) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.EntityMonster.damageEntity(EntityMonster.java:44) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:768) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.EntityCreeper.die(EntityCreeper.java:135) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:830) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:346) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:08 [Server] INFO org.bukkit.event.EventException
27.02 16:41:08 [Server] ERROR Could not pass event EntityDeathEvent to Quests v2.2.3
27.02 16:41:06 [Server] WARN kittycatella moved wrongly!
27.02 16:41:06 [Server] INFO ... 22 more
27.02 16:41:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
27.02 16:41:06 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
27.02 16:41:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
27.02 16:41:06 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
27.02 16:41:06 [Server] INFO at me.blackvein.quests.PlayerListener.onEntityDeath(PlayerListener.java:655) ~[?:?]
27.02 16:41:06 [Server] INFO Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
27.02 16:41:06 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
27.02 16:41:06 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:11) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInUseEntity.a(SourceFile:52) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1245) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.EntityPlayer.attack(EntityPlayer.java:1036) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.EntityHuman.attack(EntityHuman.java:996) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.EntityMonster.damageEntity(EntityMonster.java:44) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.damageEntity(EntityLiving.java:768) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.EntityCreeper.die(EntityCreeper.java:135) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at net.minecraft.server.v1_8_R1.EntityLiving.die(EntityLiving.java:830) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:346) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
27.02 16:41:06 [Server] INFO org.bukkit.event.EventException
27.02 16:41:06 [Server] ERROR Could not pass event EntityDeathEvent to Quests v2.2.3
27.02 16:41:04 [Server] WARN kittycatella moved wrongly!
27.02 16:41:03 [Server] INFO [ATHENA]Cecily_Thorick: theyre all for sale except the white one and the peanut butter colored one
27.02 16:40:56 [Server] INFO 827 Phrase(s) loaded.
27.02 16:40:56 [Server] INFO 5 Event(s) loaded.
27.02 16:40:56 [Server] INFO 41 Quest(s) loaded.
27.02 16:40:56 [Server] INFO quests has been loaded and enabled.
27.02 16:40:56 [Server] INFO Enabling Quests v2.2.3
27.02 16:40:52 [Server] INFO AnnabethChase was shot by Skeleton
27.02 16:40:51 [Server] INFO Quests has been unloaded.
27.02 16:40:51 [Server] INFO Disabled.
27.02 16:40:51 [Server] ERROR Quester not found for UUID "257d1f89-2cd8-4f1f-807c-da521b3cd233". Consider adding it to the Quester blacklist.
27.02 16:40:51 [Server] INFO Saving Quester data.
27.02 16:40:51 [Server] INFO Disabling Quests v2.2.2
27.02 16:40:45 [Server] INFO Evan11 tried to swim in lava
27.02 16:40:35 [Server] INFO [GLADIATRIX]⋙―⊳June_Iparis: welcome back
27.02 16:40:33 [Server] INFO [ATHENA]Cecily_Thorick: wb
27.02 16:40:30 [Server] INFO [GLADIATRIX]⋙―⊳June_Iparis: weba
27.02 16:40:27 [Multicraft] SilverSamerai03 ran command Message of the Day
27.02 16:40:27 [Connect] User SilverSamerai03, IP 65.74.101.168
27.02 16:40:27 [Server] INFO UUID of player SilverSamerai03 is 81692f43-daf8-441e-9e1f-dd85daf14c00
27.02 16:40:20 [Server] INFO [GLADIATRIX]⋙―⊳June_Iparis: xD
27.02 16:40:16 [Server] INFO [ATHENA]Cecily_Thorick: it's okay Paddy
27.02 16:40:13 [Server] INFO [INVIDIA]ʒ①ƹIggy_Ozaleaᶔ⚵ᶓ: Nothing
27.02 16:40:09 [Server] INFO [PLUTO]ʒ③ƹ⁆ᵴᴘϙʀ⁅Padfoot_Black: wat?
27.02 16:40:08 [Server] INFO [INVIDIA]ʒ①ƹIggy_Ozaleaᶔ⚵ᶓ: I love Kittay
27.02 16:40:07 [Server] INFO [PLUTO]ʒ③ƹ⁆ᵴᴘϙʀ⁅Padfoot_Black: um..
27.02 16:40:05 [Server] ERROR Quester not found for UUID "257d1f89-2cd8-4f1f-807c-da521b3cd233". Consider adding it to the Quester blacklist.
27.02 16:40:04 [Server] ERROR Quester not found for UUID "257d1f89-2cd8-4f1f-807c-da521b3cd233". Consider adding it to the Quester blacklist.
27.02 16:40:04 [Server] INFO [ATHENA]Cecily_Thorick: ;n;
27.02 16:39:59 [Server] INFO [VENUS]Maddison_Heart: well that fish i got it died :,(
27.02 16:39:35 [Server] INFO [ATHENA]Cecily_Thorick: okay Lulu tpa
27.02 16:39:31 [Server] ERROR Quester not found for UUID "257d1f89-2cd8-4f1f-807c-da521b3cd233". Consider adding it to the Quester blacklist.
27.02 16:39:31 [Server] ERROR Quester not found for UUID "257d1f89-2cd8-4f1f-807c-da521b3cd233". Consider adding it to the Quester blacklist.
27.02 16:39:30 [Server] ERROR Quester not found for UUID "257d1f89-2cd8-4f1f-807c-da521b3cd233". Consider adding it to the Quester blacklist.
```

I had actually loaded Build# 36 yesterday in an effort to stop the Quester Not Found issue, but clearly that didn't work either as you can see, since it was occurring right up until the point I loaded 2.2.3 Build# 40.

Currently the console is solid errors regarding the entity error. Which I see one with a slightly different error to it

http://pastebin.com/cBXcDMdf
(again, reverse order as a normal console, sorry)

Also, once again, going back to Build# 36 still has the UUID issues, so I'll probably go back to Build# 27, which was the build I updated from. The only issue it had for us (that I was aware of) is players could have multiple quests but had to complete or quit ALL quests that were taken before it. If they even had all the objectives completed, they simply weren't able to talk to the NPC to complete it or hand items in. Either way, comparatively a minor issue :P

**Comment by FlyingPikachu** [comment]
Quests v2.2.4 should resolve that console spam: http://www.spigotmc.org/resources/quests.3711/update?update=15610

**Comment by Formula350** [comment]
Unfortunately v2.2.4 did not solve the problem, which I made sure to test this with a restart. Ran on the test server, which had an outdated CB built from Dec 25th (which the log is using), but unfortunately even once updated to the latest functioning version I have (from Jan 22nd) the error stays the same.
``` javascript
[14:48:40] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Quests v2.2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:242) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInFlying.a(SourceFile:126) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PacketPlayInPositionLook.a(SourceFile:18) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_72]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:643) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at me.blackvein.quests.PlayerListener.onPlayerMove(PlayerListener.java:911) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	... 15 more
```

**Comment by Formula350** [comment]
And of course I forget to post the log... The above error is from the updated bukkit.

I decided to just put up the entire startup log, detailing everything I run, as who knows maybe it's a conflict. Which just now I thought perhaps SuperVanish, but even after unloading it the error still crops up.

I included some notes that detail my diagnosing steps, which you can locate by searching for ###
http://dev.bukkit.org/paste/11767/

**Comment by Formula350** [comment]
Here's another one, from disconnecting (also using build# 42)

``` javascript
[15:16:34] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to Quests v2.2.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerList.disconnect(PlayerList.java:299) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:801) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.NetworkManager.l(NetworkManager.java:229) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(SourceFile:148) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:718) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit_dev.jar:git-Bukkit-1092acb]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
	at me.blackvein.quests.PlayerListener.onPlayerQuit(PlayerListener.java:866) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit_dev.jar:git-Bukkit-1092acb]
	... 13 more
```

Also, I just updated to the latest build of CB, which thankfully does NOT break tons of plugins like last build... However, error still persists with Quests :\
http://dev.bukkit.org/paste/11768/

**Comment by FlyingPikachu** [comment]
Seems like v2.2.4 did resolve your original error; what you posted is a new error that already being addressed in ticket #37. If you wouldn't mind posting there with your server's Java version, it'd be a great help. Thanks!
