### ISSUE TITLE
Quest's Not Appearing In-Game

### ISSUE THREAD

**Issue by Chrydor** [FlyingPikachu/Quests#518]
(__Required__) What is your Quests version / build number (do _not_ say "latest")?
 - I am running Quest's 3.4.0 on a Minecraft 1.10.2 Server
(__Required__) Please describe the problem and how to replicate it. Any console errors?
- The Quests I have configured are not appearing in Game apart from the first one. (The name of the appearing Quest is 'Something is Wrong'.) If you want to test just copy and paste into your own server. 

Console is saying that I am missing 'fail-requirements-message' but I am confused as I definitely have them.
(__Optional__) Can you provide an example quest from quests.yml _using Pastebin.com_?
Here is a Pastebin with the Quests themselves in it. To my knowledge and understanding I have configured them all correctly. https://pastebin.com/CaPFduEp

(Ignore the Dialogue next to the NPC ID Points - I know that this causes them not to appear but I removed this before putting it into my server).

**Comment by FlyingPikachu** [comment]
Please include one of those console errors. Thanks!

**Comment by Chrydor** [comment]
Have all of them :P 

[05:43:13 ERROR]: [Quests] Requirements for Quest Goddess of Fertility is missing fail-requirement-message:
[05:43:13 ERROR]: [Quests] Requirements for Quest Wilted Flower is missing fail-requirement-message:
[05:43:13 ERROR]: [Quests] Requirements for Quest Secret of the Valley is missing fail-requirement-message:
[05:43:13 ERROR]: [Quests] Requirements for Quest Purification is missing fail-requirement-message:
[05:43:13 ERROR]: [Quests] Requirements for Quest The Tree is missing fail-requirement-message:

**Comment by FlyingPikachu** [comment]
Unfortunately, you can't use single quotes (') in your fail-requirements message. So, changing...

`You must first complete 'Goddess of Fertility'.`

...to...

`You must first complete Goddess of Fertility.`

...should resolve the issue. I'll keep this issue open until update the plugin to prevent this.

**Comment by Chrydor** [comment]
Oh damn that's a shame. Well thank you very much! 

I appreciate the help

**Comment by Chrydor** [comment]
Ok well I have just done that fix - and the Quest's are still not appearing. It is still giving me the same error message in the Console... xD

**Comment by FlyingPikachu** [comment]
Forgive me, the single quotes are used to mark the start and end of the string. So it should actually be...

`'You must first complete Goddess of Fertility.'`

**Comment by Chrydor** [comment]
That didn't work either haha xD Still receiving the same error message. 

Starting to think this plugin doesn't like me 😂😭😏

**Comment by FlyingPikachu** [comment]
Found it! In your quests file, you have...

`fail-requirements-message`

...when it should be...

`fail-requirement-message`

,,,without the "s".

**Comment by Chrydor** [comment]
damn - silly mistake by me xD Would never have picked that up haha. Appreciate that a bunch man!
